### ISSUE TITLE
你好，请假流程里的信息是在主表单填写的，这些数据是存在流程变量里的，请问有没有好的办法单独存到一张数据库表里，方便统一查询业务数据。

### ISSUE THREAD

**Issue by kittenzz** [liuguofeng-java/spring-boot-activiti7#1]

**Comment by liuguofeng-java** [comment]
这个问题 
1. 可以写一个执行监听器，在流程开始后触发 执行监听器，然后在执行执行监听器中获取主表单的流程数据，然后获取到主表单数据后你就可以保存到自己的表中了
2. 在流程表单设置中直接绑定表，这个还没有实现，后期会逐步实现
**如果你要用到此项目可以采用第一条方案，也是实现最快的**
**如果此项目帮助到了你就请关注一下吧，感谢支持**



![image](https://github.com/liuguofeng-java/spring-boot-activiti7/assets/59218624/0fae5ffe-4b16-4848-91e2-8726d91daa0d)
![image](https://github.com/liuguofeng-java/spring-boot-activiti7/assets/59218624/99584952-c088-4af6-997c-e251896bffb7)

**Comment by liuguofeng-java** [comment]
如果你要用第一中方式可以参考下面方法获取主表单
![image](https://github.com/liuguofeng-java/spring-boot-activiti7/assets/59218624/55e508e6-2023-4dd7-8921-4d4a7f59fd5b)

**Comment by kittenzz** [comment]
感谢您的回答。这里是获取主表单数据应该是一个字符串数据吧，后期实现绑定表，是可以根据动态生成的表单创建相应数据库表进行绑定吗？就表单和表字段一一对应这样

**Comment by liuguofeng-java** [comment]
方案一获取的主表单确是字符串，但是是json格式的字符串，可以把json字符串转成实体直接保存到数据库
方案二 后期的确是想要表单绑定表，现在把执行监听器、会签、历史审批记录 等功能做完后，就打算开始了

**Comment by liuguofeng-java** [comment]
已支持
